# Generated by Django 3.1.14 on 2022-05-28 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0003_authorpoliticpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsportpage',
            name='title',
            field=models.CharField(max_length=450),
        ),
        migrations.AlterField(
            model_name='authortechnologypage',
            name='title',
            field=models.CharField(max_length=450),
        ),
    ]
