# Generated by Django 3.1.14 on 2022-05-28 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0004_auto_20220529_0254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authorsportpage',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='authortechnologypage',
            name='title',
            field=models.CharField(max_length=250),
        ),
    ]
