# Generated by Django 3.1.14 on 2022-06-04 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspage', '0009_auto_20220603_1147'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorpoliticpage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='authorsportpage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='authortechnologypage',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
